# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib T:/15.83111-6/Logica-Programavel/exercicios/FPGA/FPGA.srcs/sources_1/new/1-mux.vhd
read_xdc T:/15.83111-6/Logica-Programavel/exercicios/FPGA/FPGA.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files T:/15.83111-6/Logica-Programavel/exercicios/FPGA/FPGA.srcs/constrs_1/new/constraint.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/15.83111-6/Logica-Programavel/exercicios/FPGA/FPGA.cache/wt [current_project]
set_property parent.project_dir T:/15.83111-6/Logica-Programavel/exercicios/FPGA [current_project]
synth_design -top ex1_mux -part xc7vx485tffg1157-1
write_checkpoint ex1_mux.dcp
report_utilization -file ex1_mux_utilization_synth.rpt -pb ex1_mux_utilization_synth.pb
